In [2]:
import torch
print(torch.__version__)

2.7.0+cu118


In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print("GPU is ",torch.cuda.get_device_name(0))
else:
    print("CPU is available")

GPU is available
GPU is  NVIDIA GeForce RTX 3050 Laptop GPU


In [7]:
# Empty tensor
a = torch.empty(2,3)

In [8]:
# Check type
type(a)

torch.Tensor

In [10]:
#Using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.rand(1,3)

tensor([[0.1947, 0.1980, 0.1468]])

In [22]:
torch.manual_seed(42)
torch.rand(1,3)

tensor([[0.8823, 0.9150, 0.3829]])

In [24]:
# Custom tensors

torch.tensor([[1,2],[2,3]])


tensor([[1, 2],
        [2, 3]])