In [1]:
import torch
import torch.nn as nn

In [2]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(3, 5)  # First layer: 3 input features → 5 neurons
        self.fc2 = nn.Linear(5, 1)  # Second layer: 5 neurons → 1 output
        self.activation = nn.Sigmoid()  # Activation function for output

    def forward(self, x):
        x = self.fc1(x)  # First layer
        x = self.activation(self.fc2(x))  # Second layer + activation
        return x


In [3]:
model = SimpleNN()  # Create an instance of the model

# Example input: a batch of 4 samples, each with 3 features
input_data = torch.rand(4, 3)  
print(input_data)


tensor([[0.2232, 0.5883, 0.5547],
        [0.9082, 0.9992, 0.6564],
        [0.8978, 0.8099, 0.2670],
        [0.6812, 0.8945, 0.6521]])


In [4]:
output = model(input_data)  # Forward pass

print(output)  # Display model output

tensor([[0.5542],
        [0.5723],
        [0.5350],
        [0.5698]], grad_fn=<SigmoidBackward0>)


### Introduction to tensors


#### Creating tensors
Pytorch tensors are created using torch.Tensor()

In [5]:
scalar = torch.tensor(7)
print (scalar)

tensor(7)


In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python integer
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
print(vector)
vector.ndim

tensor([7, 7])


1

In [11]:
vector = torch.tensor([[7],
                      [7]])
print(vector)
vector.ndim

tensor([[7],
        [7]])


2